comment:
  image:
    repository: baykanurov/comment
    tag: latest
  service:
    externalPort: 9292

post:
  image:
    repository: baykanurov/post
    tag: latest
  service:
    externalPort: 5000

ui:
  image:
    repository: baykanurov/ui
    tag: latest
  service:
    externalPort: 9292
