---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ui
spec:
  ingressClassName: {{ .Release.Name }}-{{ .Chart.Name }}
  rules:
  - http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: {{ .Release.Name }}-{{ .Chart.Name }}
            port:
              number: {{ .Values.service.externalPort }}
