services:
  mongo:
    container_name: post_db
    image: mongo:${MONGO_IMAGE_TAG:-4.4}
    volumes:
      - post_db:/data/db
    networks:
      - back_net
      - front_net

  ui:
    container_name: ui
    image: ${USERNAME:-baykanurov}/ui:${UI_IMAGE_TAG:-1.0}
    command: ["puma", "--debug", "-w 2"]
    ports:
      - ${UI_PORT:-9292}:9292/tcp
    volumes:
      - ../src/ui:/app:consistent
    networks:
      - front_net

  post:
    container_name: post
    image: ${USERNAME:-baykanurov}/post:${POST_IMAGE_TAG:-1.0}
    volumes:
      - ../src/post-py:/app:consistent
    networks:
      - back_net
      - front_net

  comment:
    container_name: comment
    image: ${USERNAME:-baykanurov}/comment:${COMMENT_IMAGE_TAG:-1.0}
    command: ["puma", "--debug", "-w 2"]
    volumes:
      - ../src/comment:/app:consistent
    networks:
      - back_net
      - front_net

volumes:
  post_db:

networks:
  back_net:
  front_net:
