version: '3.3'
services:
  mongo:
    container_name: post_db
    image: mongo:${MONGO_IMAGE_TAG}
    volumes:
      - post_db:/data/db
    networks:
      - back_net

  ui:
    container_name: ui
    image: ${USERNAME}/ui:${UI_IMAGE_TAG}
    ports:
      - ${UI_PORT}:9292/tcp
    networks:
      - front_net

  post:
    container_name: post
    image: ${USERNAME}/post:${POST_IMAGE_TAG}
    networks:
      - back_net
      - front_net

  comment:
    container_name: comment
    image: ${USERNAME}/comment:${COMMENT_IMAGE_TAG}
    networks:
      - back_net
      - front_net

  prometheus:
    image: ${USERNAME}/prometheus
    ports:
      - '9090:9090'
    volumes:
      - prometheus_data:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--storage.tsdb.retention=1d'
    networks:
      - back_net
      - front_net

volumes:
  post_db:
  prometheus_data:

networks:
  back_net:
  front_net:
