version: '3.3'
services:
  mongo:
    container_name: post_db
    image: mongo:${MONGO_IMAGE_TAG}
    volumes:
      - post_db:/data/db
    networks:
      - back_net
      - front_net

  ui:
    container_name: ui
    build: ./ui
    image: ${USERNAME}/ui:${UI_IMAGE_TAG}
    ports:
      - ${UI_PORT}:9292/tcp
    networks:
      - front_net

  post:
    container_name: post
    build: ./post-py
    image: ${USERNAME}/post:${POST_IMAGE_TAG}
    networks:
      - back_net
      - front_net

  comment:
    container_name: comment
    build: ./comment
    image: ${USERNAME}/comment:${COMMENT_IMAGE_TAG}
    networks:
      - back_net
      - front_net

volumes:
  post_db:

networks:
  back_net:
  front_net:
